server:
  port: 8090
spring:

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: 123
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000